tilesize: 192
windowwidth: 9
windowheight: 5
font: resources/Montserrat-Light.ttf
fontsize: 42
fontcolor: 'rgb(0,0,0)'
backgroundcolor: 'rgb(0,255,0)'
displaymode: name
resetkey: alt+g
pollingratehz: 50
keyimage: resources/key1.png
keyimage_dark: resources/key1_dark.png
keys:
  - enabled: true
    keyCode: 1
    name: 1
    x: 0
    y: 0
  - enabled: true
    keyCode: 2
    name: 2
    x: 1
    y: 0
  - enabled: true
    keyCode: 3
    name: 3
    x: 2
    y: 0
  - enabled: true
    keyCode: 4
    name: 4
    x: 3
    y: 0
  - enabled: true
    keyCode: 5
    name: 5
    x: 4
    y: 0
  - enabled: true
    keyCode: 6
    name: 6
    x: 5
    y: 0
  - enabled: true
    keyCode: 7
    name: 7
    x: 6
    y: 0
  - enabled: true
    keyCode: 8
    name: 8
    x: 7
    y: 0
  - enabled: true
    keyCode: 9
    name: 9
    x: 8
    y: 0
  - enabled: true
    keyCode: q
    name: q
    x: 1
    y: 1
  - enabled: true
    keyCode: w
    name: w
    x: 2
    y: 1
  - enabled: true
    keyCode: e
    name: e
    x: 3
    y: 1
  - enabled: true
    keyCode: r
    name: r
    x: 4
    y: 1
  - enabled: true
    keyCode: t
    name: t
    x: 5
    y: 1
  - enabled: true
    keyCode: a
    name: a
    x: 1.25
    y: 2
  - enabled: true
    keyCode: s
    name: s
    x: 2.25
    y: 2
  - enabled: true
    keyCode: d
    name: d
    x: 3.25
    y: 2
  - enabled: true
    keyCode: f
    name: f
    x: 4.25
    y: 2
  - enabled: true
    keyCode: z
    name: z
    x: 1.75
    y: 3
  - enabled: true
    keyCode: x
    name: x
    x: 2.75
    y: 3
  - enabled: true
    keyCode: c
    name: c
    x: 3.75
    y: 3
  - enabled: true
    keyCode: tab
    name: tab
    x: 0
    y: 2
  - enabled: true
    keyCode: shift
    name: shift
    x: 0
    y: 3
  - enabled: true
    keyCode: space
    name: space
    x: 3.5
    y: 4
  - enabled: true
    keyCode: esc
    name: esc
    x: 0
    y: 1
  - enabled: true
    keyCode: /
    name: /
    x: 0
    y: 4
  - enabled: true
    keyCode: mouse_left
    name: lmb
    x: 7
    y: 4
  - enabled: true
    keyCode: mouse_right
    name: rmb
    x: 8
    y: 4
  - enabled: true
    keyCode: mouse_middle
    name: mmb
    x: 7.5
    y: 3