tilesize: 192
windowwidth: 3
windowheight: 1
font: resources/Montserrat-Light.ttf
fontsize: 45
fontcolor: 'rgb(0,0,0)'
backgroundcolor: 'rgb(0,255,0)'
displaymode: both
resetkey: alt+g
pollingratehz: 50
keyimage: resources/key1.png
keyimage_dark: resources/key1_dark.png
keys:
  - enabled: true
    keyCode: z
    name: k1
    x: 0
    y: 0
  - enabled: true
    keyCode: ctrl+c
    name: k2
    x: 1
    y: 0
  - enabled: true
    keyCode: mouse_left
    name: lmb
    x: 2
    y: 0
