tilesize: 192
windowwidth: 5
windowheight: 1
font: resources/Montserrat-Light.ttf
fontsize: 45
fontcolor: 'rgb(255,255,255)'
backgroundcolor: 'rgb(0,0,0)'
displaymode: both
resetkey: alt+g
pollingratehz: 250
keyimage: resources/key1A_nobg.png
keyimage_dark: resources/key1A_dark.png
keys:
  - enabled: true
    keyCode: x
    name: x
    x: 0
    y: 0
  - enabled: true
    keyCode: c
    name: c
    x: 1
    y: 0
  - enabled: true
    keyCode: ','
    name: ','
    x: 3
    y: 0
  - enabled: true
    keyCode: '.'
    name: '.'
    x: 4
    y: 0
cps-enable: true
cps-x: 2
cps-y: 0


